/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.conversor.interfaz;

/**
 *
 * @author Abrah
 */
public class Vista extends javax.swing.JFrame {

    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        conversionesTabPane = new javax.swing.JTabbedPane();
        divisasPanel = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        temperaturasPanel = new javax.swing.JPanel();
        longitudPanel = new javax.swing.JPanel();
        masaPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        conversionesTabPane.setBackground(new java.awt.Color(153, 255, 255));
        conversionesTabPane.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        divisasPanel.setMaximumSize(new java.awt.Dimension(200, 100));
        divisasPanel.setPreferredSize(new java.awt.Dimension(100, 0));

        jTextField1.setText("jTextField1");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/conversor/interfaz/resources/1031527_arrow_arrow left right_arrows_double_double arrow_icon.png"))); // NOI18N

        javax.swing.GroupLayout divisasPanelLayout = new javax.swing.GroupLayout(divisasPanel);
        divisasPanel.setLayout(divisasPanelLayout);
        divisasPanelLayout.setHorizontalGroup(
            divisasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisasPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        divisasPanelLayout.setVerticalGroup(
            divisasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(divisasPanelLayout.createSequentialGroup()
                .addGroup(divisasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(divisasPanelLayout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(divisasPanelLayout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        conversionesTabPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/com/conversor/interfaz/resources/dollar-coin-money_icon-icons.com_56177.png")), divisasPanel); // NOI18N

        javax.swing.GroupLayout temperaturasPanelLayout = new javax.swing.GroupLayout(temperaturasPanel);
        temperaturasPanel.setLayout(temperaturasPanelLayout);
        temperaturasPanelLayout.setHorizontalGroup(
            temperaturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        temperaturasPanelLayout.setVerticalGroup(
            temperaturasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        conversionesTabPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/com/conversor/interfaz/resources/temperature_13519.png")), temperaturasPanel); // NOI18N

        javax.swing.GroupLayout longitudPanelLayout = new javax.swing.GroupLayout(longitudPanel);
        longitudPanel.setLayout(longitudPanelLayout);
        longitudPanelLayout.setHorizontalGroup(
            longitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        longitudPanelLayout.setVerticalGroup(
            longitudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        conversionesTabPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/com/conversor/interfaz/resources/length_5360.png")), longitudPanel); // NOI18N

        javax.swing.GroupLayout masaPanelLayout = new javax.swing.GroupLayout(masaPanel);
        masaPanel.setLayout(masaPanelLayout);
        masaPanelLayout.setHorizontalGroup(
            masaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 426, Short.MAX_VALUE)
        );
        masaPanelLayout.setVerticalGroup(
            masaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        conversionesTabPane.addTab("", new javax.swing.ImageIcon(getClass().getResource("/com/conversor/interfaz/resources/kilogram_122329.png")), masaPanel); // NOI18N

        getContentPane().add(conversionesTabPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane conversionesTabPane;
    private javax.swing.JPanel divisasPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel longitudPanel;
    private javax.swing.JPanel masaPanel;
    private javax.swing.JPanel temperaturasPanel;
    // End of variables declaration//GEN-END:variables

    
}
